#!/bin/sh

# $FreeBSD$
#
# PROVIDE: tunneld
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# tunneld_enable (bool): Set to NO be default
#                       Set it to YES to enable tunneld.

. /etc/rc.subr

name=tunneld
rcvar=tunneld_enable

load_rc_config ${name}

: ${tunneld_enable:=no}

command="/home/tunnel/bin/${name}"
pidfile=/var/run/${name}.pid

tunnel_1="/bin/sh -c \\\"sleep 10; touch /tmp/11101\\\""
command_args="-d -c \"${tunnel_1}\""
echo $command_args

run_rc_command "$1"
